Repository LutfiyaCharfaray/Low-Cost-Tremor-Assessment-22G34, pull requests merged in 2022-10, with the labels that each got.

#24 bug fixes to checkbox2
  main.py
  tremor.kv
Labels: bug

#23 Undo button
  main.py
  tremor.kv
Labels: bug, user story

#27 Timer2
  main.py
  tremor.kv
Labels: user story

#28 Coordinates
  blue.jpeg
  main.py
  patientinfo.db
  tremor.kv
Labels: enhancement

#30 Visual Rating Sliders added
  main.py
  tremor.kv
Labels: user story

#32 Results page UI changes
  __pycache__/sp.cpython-310.pyc
  tremor.kv
Labels: enhancement

#33 Results db
  .gitignore
  __pycache__/sp.cpython-310.pyc
  main.py
  tremor.kv
Labels: user story

#34 Edits2
  __pycache__/sp.cpython-310.pyc
  main.py
  tremor.kv
Labels: enhancement, user story

#35 Unit tests
  main.py
  patientinfo.db
  spiraltemp.PNG
  test images/dominant hand_template.png
  test images/non-dom hand_temp.png
  test images/normal case_resized_image.png
  test images/spiraltemp_resized_image.png
  test images/tremor case_dh.png
  test images/tremor case_ndh.png
  test images/tremor casedh_resized_image.png
  test images/tremor casendh_resized_image.png
  test_main.py
  tremor.kv
Labels: enhancement, testing

#40 Unittests2
  main.py
  test_main.py
Labels: enhancement

#43 Tremor notif
  __pycache__/sp.cpython-310.pyc
  main.py
  test_main.py
  tremor.kv
Labels: user story
